-- Insert missing movements found in the dictionary
INSERT INTO public.movements (category, slug, name, aliases)
VALUES
  ('accessory', 'sumo-deadlift', 'Sumo Deadlift', ARRAY['sumo deadlifts', 'sumo deadlift']),
  ('accessory', 'sumo-deadlift-high-pull', 'Sumo Deadlift High Pull', ARRAY['sumo deadlift high pulls', 'sumo deadlift high pull', 'sumo deadlift high-pulls', 'sumo deadlift high-pull']),
  ('accessory', 'romanian-deadlift', 'Romanian Deadlift', ARRAY['romanian deadlifts', 'romanian deadlift', 'rdl', 'rdl''s', 'rdls']),
  ('accessory', 'floor-press', 'Floor Press', ARRAY['floor-presses', 'floor-press', 'floor presses', 'floor press']),
  ('accessory', 'dumbbell-press', 'Dumbbell Press', ARRAY['db-presses', 'db-press', 'db presses', 'db press', 'dumbbell-presses', 'dumbbell-press', 'dumbbell presses', 'dumbbell press', 'dumb-bell presses', 'dumb-bell press']),
  ('accessory', 'shoulder-to-overhead', 'Shoulder to Overhead', ARRAY['shoulder-to-overheads', 'shoulder-to-overhead', 'stoh', 'stohs', 's2oh']),
  ('accessory', 'high-pull', 'High Pull', ARRAY['high pulls', 'high pull', 'high-pulls', 'high-pull']),
  ('accessory', 'barbell-row', 'Barbell Row', ARRAY['rows', 'barbell row', 'barbell rows']),
  ('accessory', 'wall-ball', 'Wall Ball', ARRAY['wall-ball shots', 'wall-ball shot', 'wallball shots', 'wallball shot', 'wall-balls', 'wall-ball', 'wallballs', 'wallball', 'wall balls', 'wall ball']),
  ('accessory', 'farmers-carry', 'Farmer''s Carry', ARRAY['farmer''s carries', 'farmers carries', 'farmer carries', 'farmer''s carry', 'farmers carry', 'farmer carry']),
  ('accessory', 'devils-press', 'Devil''s Press', ARRAY['devil''s press', 'devil''s presses', 'devil press', 'devil presses', 'devils press', 'devils presses']),
  ('accessory', 'kettlebell-swing', 'Kettlebell Swing', ARRAY['kb-swing', 'kb swing', 'kettlebell swing', 'kettle-bell swing', 'kettle bell swing', 'kb-swings', 'kb swings', 'kettlebell swings', 'kettle-bell swings', 'kettle bell swings']),
  ('accessory', 'russian-swing', 'Russian Swing', ARRAY['russian-swing', 'russian swing', 'russian kettlebell swing', 'russian kettle-bell swing', 'russian kettle bell swing', 'russian kb swing', 'russian-swings', 'russian swings', 'russian kettlebell swings', 'russian kettle-bell swings', 'russian kettle bell swings', 'russian kb swings']),
  ('accessory', 'chin-up', 'Chin-up', ARRAY['chin-over-bars', 'chin-over-bar', 'chin-ups', 'chin-up']),
  ('accessory', 'dip', 'Dip', ARRAY['dips', 'dip']),
  ('accessory', 'ring-dip', 'Ring Dip', ARRAY['ring dips', 'ring dip', 'ring-dips', 'ring-dip']),
  ('accessory', 'knees-to-elbows', 'Knees to Elbows', ARRAY['knees-to-elbows']),
  ('accessory', 'wall-walk', 'Wall Walk', ARRAY['wall walks']),
  ('accessory', 'rope-climb', 'Rope Climb', ARRAY['rope ascents', 'rope ascent', 'rope climbs', 'rope climb']),
  ('accessory', 'legless-rope-climb', 'Legless Rope Climb', ARRAY['legless rope ascents', 'legless rope ascent', 'legless rope climbs', 'legless rope climb']),
  ('accessory', 'goblet-squat', 'Goblet Squat', ARRAY['goblet squats', 'goblet squat', 'goblets', 'goblet']),
  ('accessory', 'air-squat', 'Air Squat', ARRAY['air squats', 'air squat', 'squats', 'squat']),
  ('accessory', 'sit-up', 'Sit-up', ARRAY['sit-ups', 'sit-up', 'sit ups', 'sit up']),
  ('accessory', 'ghd-sit-up', 'GHD Sit-up', ARRAY['ghd sit-ups', 'ghd sit-up', 'ghd sit ups', 'ghd sit up']),
  ('accessory', 'v-up', 'V-up', ARRAY['v-ups', 'v-up', 'v ups', 'v up']),
  ('accessory', 'burpee', 'Burpee', ARRAY['burpees', 'burpee']),
  ('accessory', 'bar-facing-burpee', 'Bar-Facing Burpee', ARRAY['burpees-over-bar', 'burpee-over-bar', 'bar-facing burpee', 'bar-facing burpees']),
  ('accessory', 'target-burpee', 'Target Burpee', ARRAY['burpees-to-rings', 'burpee-to-rings', 'burpees-to-ring', 'burpee-to-ring', 'burpees-to-target', 'burpee-to-target']),
  ('accessory', 'broad-jump', 'Broad Jump', ARRAY['broad jumps', 'broad jump', 'broad-jumps', 'broad-jump']),
  ('accessory', 'box-jump', 'Box Jump', ARRAY['box jumps', 'box jump', 'box-jumps', 'box-jump']),
  ('accessory', 'box-jump-over', 'Box Jump Over', ARRAY['box jump-overs', 'box jump-over', 'box jumps over', 'box jump over', 'box-jumps over', 'box-jump over']),
  ('accessory', 'box-step-up', 'Box Step-up', ARRAY['box step-ups', 'box step-up', 'box steps', 'box step']),
  ('accessory', 'box-step-over', 'Box Step-over', ARRAY['box step-overs', 'box step-over', 'box step overs', 'box step over']),
  ('accessory', 'lunge', 'Lunge', ARRAY['lunge', 'lunges']),
  ('accessory', 'back-lunge', 'Back Lunge', ARRAY['back lunge', 'back lunges']),
  ('accessory', 'walking-lunge', 'Walking Lunge', ARRAY['walking lunge', 'walking lunges']),
  ('accessory', 'dumbbell-overhead-lunge', 'Dumbbell Overhead Lunge', ARRAY['dumbbell overhead lunge', 'dumbbell overhead lunges']),
  ('accessory', 'ghd-back-extension', 'GHD Back Extension', ARRAY['GHD back extensions', 'GHD back extension']),
  ('accessory', 'ghd-hip-extension', 'GHD Hip Extension', ARRAY['GHD hip extensions', 'GHD hip extension']),
  ('accessory', 'shuttle-run', 'Shuttle Run', ARRAY['shuttle runs', 'shuttle run', 'shuttle-runs', 'shuttle-run']),
  ('accessory', 'single-under', 'Single-under', ARRAY['single-unders', 'single unders', 'single-under', 'single under']),
  ('accessory', 'triple-under', 'Triple-under', ARRAY['triple-unders', 'triple unders', 'triple-under', 'triple under']),
  ('accessory', 'squat-hold', 'Squat Hold', ARRAY['squat hold', 'squat-hold']),
  ('accessory', 'chin-up-hold', 'Chin-up Hold', ARRAY['chin-over-bar hold', 'chin up hold', 'chin-up hold'])
ON CONFLICT (slug) DO UPDATE 
SET aliases = EXCLUDED.aliases;